[build]
 functions = "./api"
 publish = "build/"

[[redirects]]
 from = "/static/*"
 to = "/build/static/:splat"
 status = 200

[[redirects]]
 from = "/api/*"
 to = "/.netlify/functions/:splat"
 status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/api/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"

[build.environment]
NODE_VERSION = "14.16.0"

[functions]
node_bundler = "esbuild"
